import random
import itertools
import time
import smtplib
str_s = "UFSUFBMCWFQKSWRSWFSYSQXJSYJFSYSIBMCWFQKSASSGQJRTSXBYUMZFQIBYWJBTBYYBIQGWJBTBYYBIQGWJBTBYYBIZYSSNURGJFRUNSJJLNQZSXYBTWQLJBWQLJBJFSCQUJULCCQACSBXYSZBYWSWJRTSQGWQCCBMYLSUJSYWQLUFQKSCRVFJSWXBBCUJFSIQLJBWMUJLWSQJFBMJBMJAYRSXZQGWCSCRXSUAMJQIQCDRGVUFQWBIQNBBYNCQLSYJFQJUJYMJUQGWXYSJUFRUFBMYMNBGJFSUJQVSQGWJFSGRUFSQYWGBTBYSRJRUQJQCSJBCWALQGRWRBJXMCCBXUBMGWQGWXMYLURVGRXLRGVGBJFRGV"
key = "abcdefghijklmnopqrstuvwxyz".upper()
import itertools 
for word in itertools.permutations( list(key) ):
    if ''.join(word)=='qazwsxvfrpdctgbnoyujmkielh':
    	print "eureka"
    	print ''.join(word)
   
